-- =====================================================
-- 05_kpis.sql
-- Logistics Operations & Fleet Performance Analysis
-- Key Performance Indicators
-- =====================================================

USE logistics_operations;

-- =====================================================
-- 1. TOTAL LOADS
-- =====================================================

-- KPI:
-- Total number of loads handled by the company.

SELECT
    COUNT(*) AS total_loads
FROM loads;

/*
Result:
85,410 total loads.

Interpretation:
The company handled 85,410 loads during the analyzed period.
*/

-- =====================================================
-- 2. TOTAL REVENUE
-- =====================================================

-- KPI:
-- Total revenue generated by all loads.

SELECT
    ROUND(SUM(revenue), 2) AS total_revenue
FROM loads;

/*
Result:
262,525,800.29 total revenue.

Interpretation:
The company generated approximately 262.53M in revenue
during the analyzed period.
*/

-- =====================================================
-- 3. AVERAGE REVENUE PER LOAD
-- =====================================================

-- KPI:
-- Average revenue generated per load.

SELECT
    ROUND(AVG(revenue), 2) AS avg_revenue_per_load
FROM loads;

/*
Result:
3,073.71 average revenue per load.

Interpretation:
Each load generated approximately 3,073.71 in revenue on average.
*/

-- =====================================================
-- 4. TOTAL MILES
-- =====================================================

-- KPI:
-- Total actual miles traveled across all trips.

SELECT
    ROUND(SUM(actual_distance_miles), 2) AS total_miles
FROM trips;

/*
Result:
122,159,201 total miles.

Interpretation:
The company traveled approximately 122.16 million miles
during the analyzed period.
*/

-- =====================================================
-- 5. AVERAGE MPG
-- =====================================================

-- KPI:
-- Overall fuel efficiency across all trips.

SELECT
    ROUND(
        SUM(actual_distance_miles) / NULLIF(SUM(fuel_gallons_used), 0),
        2
    ) AS avg_mpg
FROM trips;

/*
Result:
6.45 MPG.

Interpretation:
The fleet achieved an overall fuel efficiency of approximately
6.45 miles per gallon across all trips.
*/

-- =====================================================
-- 6. AVERAGE IDLE HOURS
-- =====================================================

-- KPI:
-- Average idle time per trip.

SELECT
    ROUND(AVG(idle_time_hours), 2) AS avg_idle_hours
FROM trips;

/*
Result:
7.01 average idle hours per trip.

Interpretation:
Trips recorded an average of approximately 7.01 idle hours.

This metric should be interpreted cautiously because some trips
have idle time values greater than actual trip duration.
*/

-- =====================================================
-- 7. ON-TIME DELIVERY RATE
-- =====================================================

-- KPI:
-- Percentage of delivery events completed on time.

SELECT
    ROUND(
        AVG(on_time_flag) * 100,
        2
    ) AS on_time_delivery_rate
FROM delivery_events
WHERE event_type = 'Delivery';

/*
Result:
44.61% on-time delivery rate.

Interpretation:
Approximately 44.61% of deliveries were completed on time,
indicating a significant opportunity to improve delivery reliability.
*/

-- =====================================================
-- 8. AVERAGE DETENTION MINUTES
-- =====================================================

-- KPI:
-- Average detention time for delivery events.

SELECT
    ROUND(AVG(detention_minutes), 2) AS avg_detention_minutes
FROM delivery_events
WHERE event_type = 'Delivery';

/*
Result:
106.60 average detention minutes.

Interpretation:
Delivery events recorded an average detention time of approximately
106.60 minutes, suggesting that waiting time at delivery points
may be an important source of operational inefficiency.
*/

-- =====================================================
-- 9. TOTAL FUEL COST
-- =====================================================

-- KPI:
-- Total cost of fuel purchases.

SELECT
    ROUND(SUM(total_cost), 2) AS total_fuel_cost
FROM fuel_purchases;

/*
Result:
95,592,992.04 total fuel cost.

Interpretation:
The company recorded approximately 95.59M in fuel costs,
making fuel one of the most significant operating cost components.
*/

-- =====================================================
-- 10. FUEL COST PER MILE
-- =====================================================

-- KPI:
-- Average fuel cost per mile traveled.

WITH fuel_by_trip AS (
    SELECT
        trip_id,
        SUM(total_cost) AS fuel_cost
    FROM fuel_purchases
    GROUP BY trip_id
)

SELECT
    ROUND(
        SUM(f.fuel_cost) / NULLIF(SUM(t.actual_distance_miles), 0),
        2
    ) AS fuel_cost_per_mile
FROM fuel_by_trip f
JOIN trips t
    ON f.trip_id = t.trip_id;

/*
Result:
0.87 fuel cost per mile.

Interpretation:
The company spent approximately 0.87 in fuel
for every mile traveled.
*/

-- =====================================================
-- 11. TOTAL MAINTENANCE COST
-- =====================================================

-- KPI:
-- Total maintenance cost for the truck fleet.

SELECT
    ROUND(SUM(total_cost), 2) AS total_maintenance_cost
FROM maintenance_records;

/*
Result:
5,730,573.28 total maintenance cost.

Interpretation:
The company recorded approximately 5.73M in maintenance costs
for the truck fleet during the analyzed period.
*/

-- =====================================================
-- 12. TOTAL DOWNTIME HOURS
-- =====================================================

-- KPI:
-- Total truck downtime caused by maintenance.

SELECT
    ROUND(SUM(downtime_hours), 2) AS total_downtime_hours
FROM maintenance_records;

/*
Result:
72,230.50 total downtime hours.

Interpretation:
The fleet accumulated approximately 72.23K hours of downtime
associated with maintenance events during the analyzed period.
*/